name        : gtk-theme-bluebird
version     : 1.2
release     : 3
source      :
    - https://github.com/shimmerproject/Bluebird/archive/v1.2.tar.gz : f76520181d9cb74a0cf1c61728ab02a7fb5f0835fef036ebd68f1e89caa0c579
homepage    : http://shimmerproject.org/project/bluebird/
license     : GPL-2.0
summary     : GTK Theme Suite - Bluebird
description : |
    GTK Theme Suite - Bluebird
setup      : |
build      : |
install    : |
    mkdir -p %installroot%/usr/share/themes/BlueBird
    mv * %installroot%/usr/share/themes/BlueBird/
